name: Generate Snake Animation

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v3

      - name: Gerar Animação Snake
        uses: Platane/snk@v3
        with:
          github_user_name: LinconAvila
          svg_path: github-snake.svg
          dark_svg_path: github-snake-dark.svg
          generate_dark_variant: true

      - name: Commit e Push das Mudanças
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout --orphan output
          git reset --hard
          git add -f *.svg
          git commit -m "Atualizando a animação Snake"
          git push origin output --force
        continue-on-error: true
